//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhamoLauncher.Charts {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhamoLauncher.Charts.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir &amp;gráfico.
        /// </summary>
        internal static string AddChart {
            get {
                return ResourceManager.GetString("AddChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series disponibles.
        /// </summary>
        internal static string AllSeries {
            get {
                return ResourceManager.GetString("AllSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  / .
        /// </summary>
        internal static string AxisTitleSeparator {
            get {
                return ResourceManager.GetString("AxisTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string ChartOptionsCaption {
            get {
                return ResourceManager.GetString("ChartOptionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}. {1}.
        /// </summary>
        internal static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar gráficos &amp;personalizados.
        /// </summary>
        internal static string CreateCustomCharts {
            get {
                return ResourceManager.GetString("CreateCustomCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar gráfico por &amp;serie.
        /// </summary>
        internal static string CreateDefaultCharts {
            get {
                return ResourceManager.GetString("CreateDefaultCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;No generar gráficos.
        /// </summary>
        internal static string CreateNoCharts {
            get {
                return ResourceManager.GetString("CreateNoCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WhamoLauncher.Charts no se ha ejecutado correctamente. Se ha producido el siguiente error: {0}.
        /// </summary>
        internal static string CriticalErrorMessage {
            get {
                return ResourceManager.GetString("CriticalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráficos personalizados.
        /// </summary>
        internal static string CustomCharts {
            get {
                return ResourceManager.GetString("CustomCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráfico {0}.
        /// </summary>
        internal static string ExcelChartSheetName {
            get {
                return ResourceManager.GetString("ExcelChartSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xls.
        /// </summary>
        internal static string ExcelFileExtension {
            get {
                return ResourceManager.GetString("ExcelFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato.
        /// </summary>
        internal static string FormatExceptionCaption {
            get {
                return ResourceManager.GetString("FormatExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo tiene un formato incorrecto y no se puede leer..
        /// </summary>
        internal static string FormatExceptionMessage {
            get {
                return ResourceManager.GetString("FormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string GenericErrorCaption {
            get {
                return ResourceManager.GetString("GenericErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a grf.
        /// </summary>
        internal static string GraphTemplateFileExtension {
            get {
                return ResourceManager.GetString("GraphTemplateFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantilla desactualizada.
        /// </summary>
        internal static string InvalidOperationExceptionCaption {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La plantilla no se puede utilizar; contiene series que no se encuentran en el archivo .out del WHAMO..
        /// </summary>
        internal static string InvalidOperationExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de acceso.
        /// </summary>
        internal static string IOExceptionCaption {
            get {
                return ResourceManager.GetString("IOExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede abrir la plantilla. No tiene acceso o permiso para ello..
        /// </summary>
        internal static string IOExceptionMessage {
            get {
                return ResourceManager.GetString("IOExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar &amp;plantilla.
        /// </summary>
        internal static string LoadTemplate {
            get {
                return ResourceManager.GetString("LoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WhamoLauncher.Charts.log.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado ningún archivo de datos procesados (*.csv)..
        /// </summary>
        internal static string NoDataFileMessage {
            get {
                return ResourceManager.GetString("NoDataFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series a mostrar en eje Y principal.
        /// </summary>
        internal static string PrimarySeries {
            get {
                return ResourceManager.GetString("PrimarySeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Quitar gráfico.
        /// </summary>
        internal static string RemoveChart {
            get {
                return ResourceManager.GetString("RemoveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series a mostrar en eje Y secundario.
        /// </summary>
        internal static string SecondarySeries {
            get {
                return ResourceManager.GetString("SecondarySeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1} {2}.
        /// </summary>
        internal static string SeriesHeaderName {
            get {
                return ResourceManager.GetString("SeriesHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  - .
        /// </summary>
        internal static string SeriesHeaderSeparator {
            get {
                return ResourceManager.GetString("SeriesHeaderSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Graph].
        /// </summary>
        internal static string TemplateGraphTag {
            get {
                return ResourceManager.GetString("TemplateGraphTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Primary].
        /// </summary>
        internal static string TemplatePrimaryTag {
            get {
                return ResourceManager.GetString("TemplatePrimaryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Secondary].
        /// </summary>
        internal static string TemplateSecondaryTag {
            get {
                return ResourceManager.GetString("TemplateSecondaryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error inesperado y la aplicación debe cerrarse. Para más detalles consulte el archivo de registro en &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor espere mientras se generan los gráficos.
        /// </summary>
        internal static string WaitChartsMessage {
            get {
                return ResourceManager.GetString("WaitChartsMessage", resourceCulture);
            }
        }
    }
}
