//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhamoLauncher {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhamoLauncher.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a csv.
        /// </summary>
        internal static string CsvFileExtension {
            get {
                return ResourceManager.GetString("CsvFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cs2.
        /// </summary>
        internal static string CsvSafeCopyFileExtension {
            get {
                return ResourceManager.GetString("CsvSafeCopyFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de entrada especificado &apos;{0}&apos; no existe o no tiene permiso para acceder a él..
        /// </summary>
        internal static string InputFileNotFoundError {
            get {
                return ResourceManager.GetString("InputFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta tarea ya ha concluido y sólo se puede ejecutar una vez. No es posible invocar de nuevo el método &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleInvocationsError {
            get {
                return ResourceManager.GetString("MultipleInvocationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe especificar un archivo de entrada *.inp.
        /// </summary>
        internal static string NoInputFileMessage {
            get {
                return ResourceManager.GetString("NoInputFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de salida de datos &apos;{0}&apos; está vacío..
        /// </summary>
        internal static string OutFileEmptyError {
            get {
                return ResourceManager.GetString("OutFileEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del archivo de salida de datos *.out no es válido. Comprueba que la simulación de Whamo haya finalizado correctamente..
        /// </summary>
        internal static string OutFileFormatError {
            get {
                return ResourceManager.GetString("OutFileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulse una tecla para salir....
        /// </summary>
        internal static string PressKeyToExitMessage {
            get {
                return ResourceManager.GetString("PressKeyToExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caudal.
        /// </summary>
        internal static string TranslatedDischargeHeader {
            get {
                return ResourceManager.GetString("TranslatedDischargeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (metros).
        /// </summary>
        internal static string TranslatedDistanceUnit {
            get {
                return ResourceManager.GetString("TranslatedDistanceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energía.
        /// </summary>
        internal static string TranslatedEnergyElevationHeader {
            get {
                return ResourceManager.GetString("TranslatedEnergyElevationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (m3/s).
        /// </summary>
        internal static string TranslatedFlowUnit {
            get {
                return ResourceManager.GetString("TranslatedFlowUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura.
        /// </summary>
        internal static string TranslatedOpeningHeader {
            get {
                return ResourceManager.GetString("TranslatedOpeningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cota piezométrica.
        /// </summary>
        internal static string TranslatedPiezometricHeader {
            get {
                return ResourceManager.GetString("TranslatedPiezometricHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potencia.
        /// </summary>
        internal static string TranslatedPowerHeader {
            get {
                return ResourceManager.GetString("TranslatedPowerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (kW).
        /// </summary>
        internal static string TranslatedPowerUnit {
            get {
                return ResourceManager.GetString("TranslatedPowerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presión.
        /// </summary>
        internal static string TranslatedPressureHeader {
            get {
                return ResourceManager.GetString("TranslatedPressureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad.
        /// </summary>
        internal static string TranslatedSpeedHeader {
            get {
                return ResourceManager.GetString("TranslatedSpeedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo.
        /// </summary>
        internal static string TranslatedTimeHeader {
            get {
                return ResourceManager.GetString("TranslatedTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (s).
        /// </summary>
        internal static string TranslatedTimeUnit {
            get {
                return ResourceManager.GetString("TranslatedTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Par.
        /// </summary>
        internal static string TranslatedTorqueHeader {
            get {
                return ResourceManager.GetString("TranslatedTorqueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (kN·m).
        /// </summary>
        internal static string TranslatedTorqueUnit {
            get {
                return ResourceManager.GetString("TranslatedTorqueUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        internal static string TranslatedWaterElevationHeader {
            get {
                return ResourceManager.GetString("TranslatedWaterElevationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WHAMO.EXE.
        /// </summary>
        internal static string WhamoExecutableFileName {
            get {
                return ResourceManager.GetString("WhamoExecutableFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo ejecutable &apos;{0}&apos; no existe o no tiene permiso para acceder a él..
        /// </summary>
        internal static string WhamoExecutableNotFoundError {
            get {
                return ResourceManager.GetString("WhamoExecutableNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a out.
        /// </summary>
        internal static string WhamoOutFileExtension {
            get {
                return ResourceManager.GetString("WhamoOutFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ou2.
        /// </summary>
        internal static string WhamoOutSafeCopyFileExtension {
            get {
                return ResourceManager.GetString("WhamoOutSafeCopyFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a plt.
        /// </summary>
        internal static string WhamoPlotFileExtension {
            get {
                return ResourceManager.GetString("WhamoPlotFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pl2.
        /// </summary>
        internal static string WhamoPlotSafeCopyFileExtension {
            get {
                return ResourceManager.GetString("WhamoPlotSafeCopyFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tab.
        /// </summary>
        internal static string WhamoTabFileExtension {
            get {
                return ResourceManager.GetString("WhamoTabFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ta2.
        /// </summary>
        internal static string WhamoTabSafeCopyFileExtension {
            get {
                return ResourceManager.GetString("WhamoTabSafeCopyFileExtension", resourceCulture);
            }
        }
    }
}
